### ISSUE TITLE
[Ongoing] Ore/Asteroid Mining 

### ISSUE THREAD

**Issue by TheRiven** [TeamPorcupine/ProjectPorcupine#1241]
## Goal
To make asteroids into more then just platforms of resources. They should be giant space rocks with resources inside them! To this end world gen is being altered to create rock that you will mine though to get to ore deposits that will then provide you with your resources.

Other changes will be made where necessary to allow this system to function as it should.

### Stage 1 - Minable Furniture - Done & Implemented - PR #1059 

- This stage sets up furniture world gen and replaces the current ore inventories with ore mineing spots.
- They are tied into the right click context menu to provide a way for the player to select which spots to mine and when.
- This also adds the Non-Buildable tag to the game so that some furniture can be made to not appear in the furniture build list (unless in dev mode).

### Stage 2 - Filling the Asteroid - Ongoing - PR #1226 

- [x] Have asteroids be filled with "rock" walls
- [x] Have some of those walls contain Ore (currently Uranium and Iron)
- [x] Allow the player to mine through the walls
- [ ] Create new Spritesheet for walls
- [ ] Have sprites for the walls with ore in them, possibly use as an overlay?
- [x] Make it so that you can mine from an adjacent tile if the object is not enterable 

## Current Issues/Bugs
- Job system does not like it when you create a mining job for furniture that cannot be reached
- Mining Jobs are not assigned to the closest worker (Somewhat annoying but I think its WAD currently?)
- Only Uranium and Iron are currently supported by this system, needs to be more generic so that other resources can be added easily

## Future (not assigned to Stage) Tasks/Stages
- Group select for mining jobs
- Mining jobs need to take time - For testing speed this has been set to 0
- Sound effects?
- Expand to cover more possible minable inventories (currently only ICE)
- Mining down/up
- Make more use of the world gen XML?
- Gas Pockets?
- Other things that might appear in an asteroid?

**Comment by Tranberry** [comment]
> - [ ] Create new Spritesheet for walls

How is that going, I'm holding on to my seat in suspense.

**Comment by TheRiven** [comment]
@Tranberry its currently in the er... conceptual stage :neutral_face:

**Comment by Tranberry** [comment]
concept like in doodle or like "I'm thinking about it"? :japanese_goblin:

**Comment by kd7uiy** [comment]
Ice should also be included, and in fact should likely be one of the major resources. I think in the future we will be using that to make rocket fuel, as well as water and oxygen and growing food, so I think it will be helpful to have a lot of it, plus it's realistic.

**Comment by TheRiven** [comment]
@kd7uiy I agree ice should be an important resource in the future, currently it does nothing but fill up space but its easy enough to add it in.

**Comment by TomMalbran** [comment]
Another cool feature is to add some fog of war over the rocks like RimWorld, so that you don't know what you are mining. It makes it more interesting.

We also need an indication as to what is marked for mining.

**Comment by Tritaris** [comment]
hey @TheRiven I started work on setting up a new noise source for map generation getting decent results from it but its still a [WIP] you can check it out here: #1244

**Comment by kd7uiy** [comment]
@TomMalbran Marking what is listed for mining sounds like a great idea! My thought is that there should be a variety of rock types, so you might know that a rock will have more water, or iron, etc, but won't know for sure until you dock. If you use some kind of a sensor, you might know before then, details not yet worked out.

**Comment by TheRiven** [comment]
@TomMalbran Fog of war would be a nice thing to get in there later, will add it to the list. :+1: 
The marking idea is something I have been thinking about as well and I think I will add it to the current stage as its a real pain to test things when you can't be sure what you have actually selected

**Comment by TomMalbran** [comment]
@kd7uiy if We implement the Fog of War, you would know what type of rock is at the edge, sy selecting it and not what is inside. A sensor could be implemented so that we can find what is in the Fog of War before mining it.

We probably should also have different types of floors, if we make it so that there are floors under the rocks. We could also just not even have floors and you see the top of the rock from underneath floor or the empty space at the bottom floor. Since we are already floating in space it makes sense to have no floors.

**Comment by dusho** [comment]
+ task for making ore resources appear in veins formations (so some continuous blobs).. size of the blob depends on rarity of material (large iron deposits, sparse uranium, ... )

**Comment by vogonistic** [comment]
Loving this thread. This is awesome!

**Comment by kd7uiy** [comment]
I actually like the idea of not knowing exactly what the rock is that you are currently mining, although finding the surface might be pretty easy. A color could be seen by default, but no specific information unless you have a sensor of some kind.

**Comment by TheRiven** [comment]
Added some pictures showing the current state of the changes in #1226

**Comment by Tranberry** [comment]
Would a font with 'dingbats' custom made for ProjectPorcupine be useful for having symbols indicating jobs (mine here) and other things like power?

**Comment by TheRiven** [comment]
Have updated the pictures to the latest version and have moved the ore sprites to the future tasks list (will probably be part of a make things pretty PR later) 

With that moved out all current tasks are now done, I am marking the current stage for review so people can see what they think and we can finally get some rock on these astros. 👍

**Comment by Tranberry** [comment]
are there three (3) tiles designated for mining in the screenshot?

**Comment by TheRiven** [comment]
yup

**Comment by dusho** [comment]
is there a reason why there is floor tile created after resources or dirt are mined? can it stay empty? then user can see layers underneath..

**Comment by TheRiven** [comment]
@dusho the tiles are not created after mining, they are there so that the walls can exist. I suppose it could also remove the floor on mining though.

**Comment by TheRiven** [comment]
Updated Stage 2 to "Done & Implemented"
