### ISSUE TITLE
Discussion: Roadmap/Milestones

### ISSUE THREAD

**Issue by WardBenjamin** [TeamPorcupine/ProjectPorcupine#228]
A lot of larger community projects that you can find on Github use the (in my opinion, great) milestone system and release system for versioning. Another option would be something like this:

[ROADMAP: VERSION #0.243378]

- [ ] TASK NUMBER ONE
- [ ] Add some cool feature
- [ ] Some amazing mechanic

Opinions?

**Comment by SquareMan** [comment]
We definitely need a larger roadmap or milestone system to guide development on the project. As it is now everyone is just sorta throwing whatever they want into the project, which isn't necessarily a bad thing, we're getting lots of new things, but we seem to be lacking in overall progression and creation of all "new" features. As such I've mostly been focusing on bug-fixing and improving on already existing features.

**Comment by koosemose** [comment]
Yeah, an idea of where this is going, and what kind of features we may look at developing would definitely be of use, both as an idea of what we might develop, and so that we can break them down and figure out what sort of supporting features we may need to build into the system. As is I've been trying to keep an eye out for any future-proofing I can do, things that work for now, but as we expand and add more objects and features may become messy and difficult to work and require a lot of rewrites.

**Comment by WardBenjamin** [comment]
Once @quill18 decides who the maintainers/whatever are, they can add issues to milestones. Right now we're generating a bunch of issues and such, and that would be a good way to keep track of them.

**Comment by sboigelot** [comment]
This issue can be close, we have a roadmap

**Comment by vogonistic** [comment]
=)
